services:
  c1-service:
    image: c1-image
    container_name: c1-container
    build:
      context: ./cont1
      dockerfile: Dockerfile
    ports:
      - 8001:8001
  c2-service:
    image: c2-image
    container_name: c2-container
    build:
      context: ./cont2
      dockerfile: Dockerfile
    ports:
      - 8002:8002